//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.SCM {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FlowStrategy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlowStrategy() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SCM.FlowStrategy", typeof(FlowStrategy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_Desc1 {
            get {
                return ResourceManager.GetString("FlowStrategy_Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strategy 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_DistributionStrategy {
            get {
                return ResourceManager.GetString("FlowStrategy_DistributionStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EmLeadTime 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_EmLeadTime {
            get {
                return ResourceManager.GetString("FlowStrategy_EmLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_Flow {
            get {
                return ResourceManager.GetString("FlowStrategy_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HaltTime 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_HaltTime {
            get {
                return ResourceManager.GetString("FlowStrategy_HaltTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Daily 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_IsCheckMrpDailyPlan {
            get {
                return ResourceManager.GetString("FlowStrategy_IsCheckMrpDailyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monthly 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_IsCheckMrpMonthlyPlan {
            get {
                return ResourceManager.GetString("FlowStrategy_IsCheckMrpMonthlyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weekly 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_IsCheckMrpWeeklyPlan {
            get {
                return ResourceManager.GetString("FlowStrategy_IsCheckMrpWeeklyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeadTime 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_LeadTime {
            get {
                return ResourceManager.GetString("FlowStrategy_LeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MrpLeadTime 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_MrpLeadTime {
            get {
                return ResourceManager.GetString("FlowStrategy_MrpLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NextOderTime 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_NextOderTime {
            get {
                return ResourceManager.GetString("FlowStrategy_NextOderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NextWindowTime 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_NextWindowTime {
            get {
                return ResourceManager.GetString("FlowStrategy_NextWindowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plan Type 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_PlanType {
            get {
                return ResourceManager.GetString("FlowStrategy_PlanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Production Strategy 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_ProductionStrategy {
            get {
                return ResourceManager.GetString("FlowStrategy_ProductionStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RccpLeadTime 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_RccpLeadTime {
            get {
                return ResourceManager.GetString("FlowStrategy_RccpLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strategy 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_Strategy {
            get {
                return ResourceManager.GetString("FlowStrategy_Strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strategy 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_SubconctractingStrategy {
            get {
                return ResourceManager.GetString("FlowStrategy_SubconctractingStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TimeUnit 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_TimeUnit {
            get {
                return ResourceManager.GetString("FlowStrategy_TimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strategy 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_TransferStrategy {
            get {
                return ResourceManager.GetString("FlowStrategy_TransferStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TrialProduceTime 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_TrialProduceTime {
            get {
                return ResourceManager.GetString("FlowStrategy_TrialProduceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlowStrategy has been Updated succssfully. 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_Updated {
            get {
                return ResourceManager.GetString("FlowStrategy_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WaitBatch 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_WaitBatch {
            get {
                return ResourceManager.GetString("FlowStrategy_WaitBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WaitTime 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_WaitTime {
            get {
                return ResourceManager.GetString("FlowStrategy_WaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hour 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_WaitTimeWithHour {
            get {
                return ResourceManager.GetString("FlowStrategy_WaitTimeWithHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeekInterval 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_WeekInterval {
            get {
                return ResourceManager.GetString("FlowStrategy_WeekInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WindowTimeType 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_WindowTimeType {
            get {
                return ResourceManager.GetString("FlowStrategy_WindowTimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinTime 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_WinTime {
            get {
                return ResourceManager.GetString("FlowStrategy_WinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monday 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_WinTime1 {
            get {
                return ResourceManager.GetString("FlowStrategy_WinTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tuesday 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_WinTime2 {
            get {
                return ResourceManager.GetString("FlowStrategy_WinTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wednesday 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_WinTime3 {
            get {
                return ResourceManager.GetString("FlowStrategy_WinTime3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wednesday 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_WinTime4 {
            get {
                return ResourceManager.GetString("FlowStrategy_WinTime4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Friday 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_WinTime5 {
            get {
                return ResourceManager.GetString("FlowStrategy_WinTime5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saturday 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_WinTime6 {
            get {
                return ResourceManager.GetString("FlowStrategy_WinTime6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sunday 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_WinTime7 {
            get {
                return ResourceManager.GetString("FlowStrategy_WinTime7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinTimeDiff 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_WinTimeDiff {
            get {
                return ResourceManager.GetString("FlowStrategy_WinTimeDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 format:08:00|10:30|15:30 的本地化字符串。
        /// </summary>
        public static string FlowStrategy_WinTimeToolTip {
            get {
                return ResourceManager.GetString("FlowStrategy_WinTimeToolTip", resourceCulture);
            }
        }
    }
}
