//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.SCM {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FlowDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlowDetail() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SCM.FlowDetail", typeof(FlowDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 FlowDetail has been Added successfully. 的本地化字符串。
        /// </summary>
        public static string FlowDetail_Added {
            get {
                return ResourceManager.GetString("FlowDetail_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BatchSize 的本地化字符串。
        /// </summary>
        public static string FlowDetail_BatchSize {
            get {
                return ResourceManager.GetString("FlowDetail_BatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BillAddress 的本地化字符串。
        /// </summary>
        public static string FlowDetail_BillAddress {
            get {
                return ResourceManager.GetString("FlowDetail_BillAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BillTerm 的本地化字符串。
        /// </summary>
        public static string FlowDetail_BillTerm {
            get {
                return ResourceManager.GetString("FlowDetail_BillTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bom 的本地化字符串。
        /// </summary>
        public static string FlowDetail_Bom {
            get {
                return ResourceManager.GetString("FlowDetail_Bom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Container 的本地化字符串。
        /// </summary>
        public static string FlowDetail_Container {
            get {
                return ResourceManager.GetString("FlowDetail_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ContainerDescription 的本地化字符串。
        /// </summary>
        public static string FlowDetail_ContainerDescription {
            get {
                return ResourceManager.GetString("FlowDetail_ContainerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentQty 的本地化字符串。
        /// </summary>
        public static string FlowDetail_CurrentQty {
            get {
                return ResourceManager.GetString("FlowDetail_CurrentQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlowDetail has been deleted successfully. 的本地化字符串。
        /// </summary>
        public static string FlowDetail_Deleted {
            get {
                return ResourceManager.GetString("FlowDetail_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EBELN 的本地化字符串。
        /// </summary>
        public static string FlowDetail_EBELN {
            get {
                return ResourceManager.GetString("FlowDetail_EBELN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EBELP 的本地化字符串。
        /// </summary>
        public static string FlowDetail_EBELP {
            get {
                return ResourceManager.GetString("FlowDetail_EBELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndDate 的本地化字符串。
        /// </summary>
        public static string FlowDetail_EndDate {
            get {
                return ResourceManager.GetString("FlowDetail_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExtraDemandSource 的本地化字符串。
        /// </summary>
        public static string FlowDetail_ExtraDemandSource {
            get {
                return ResourceManager.GetString("FlowDetail_ExtraDemandSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExtraDemandSourceFormat 的本地化字符串。
        /// </summary>
        public static string FlowDetail_ExtraDemandSourceFormat {
            get {
                return ResourceManager.GetString("FlowDetail_ExtraDemandSourceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExtraDemandSourceToolTips 的本地化字符串。
        /// </summary>
        public static string FlowDetail_ExtraDemandSourceToolTips {
            get {
                return ResourceManager.GetString("FlowDetail_ExtraDemandSourceToolTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra LocationFrom 的本地化字符串。
        /// </summary>
        public static string FlowDetail_ExtraLocationFrom {
            get {
                return ResourceManager.GetString("FlowDetail_ExtraLocationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra LocationTo 的本地化字符串。
        /// </summary>
        public static string FlowDetail_ExtraLocationTo {
            get {
                return ResourceManager.GetString("FlowDetail_ExtraLocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow 的本地化字符串。
        /// </summary>
        public static string FlowDetail_Flow {
            get {
                return ResourceManager.GetString("FlowDetail_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlowStrategy 的本地化字符串。
        /// </summary>
        public static string FlowDetail_FlowStrategy {
            get {
                return ResourceManager.GetString("FlowDetail_FlowStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuQty 的本地化字符串。
        /// </summary>
        public static string FlowDetail_HuQty {
            get {
                return ResourceManager.GetString("FlowDetail_HuQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string FlowDetail_Id {
            get {
                return ResourceManager.GetString("FlowDetail_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsAutoCreate 的本地化字符串。
        /// </summary>
        public static string FlowDetail_IsAutoCreate {
            get {
                return ResourceManager.GetString("FlowDetail_IsAutoCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsChangeUnitCount 的本地化字符串。
        /// </summary>
        public static string FlowDetail_IsChangeUnitCount {
            get {
                return ResourceManager.GetString("FlowDetail_IsChangeUnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Freeze 的本地化字符串。
        /// </summary>
        public static string FlowDetail_IsFreeze {
            get {
                return ResourceManager.GetString("FlowDetail_IsFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsInspect 的本地化字符串。
        /// </summary>
        public static string FlowDetail_IsInspect {
            get {
                return ResourceManager.GetString("FlowDetail_IsInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsRejectInspect 的本地化字符串。
        /// </summary>
        public static string FlowDetail_IsRejectInspect {
            get {
                return ResourceManager.GetString("FlowDetail_IsRejectInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        public static string FlowDetail_Item {
            get {
                return ResourceManager.GetString("FlowDetail_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ItemDescription 的本地化字符串。
        /// </summary>
        public static string FlowDetail_ItemDescription {
            get {
                return ResourceManager.GetString("FlowDetail_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LegendBaseInfo 的本地化字符串。
        /// </summary>
        public static string FlowDetail_LegendBaseInfo {
            get {
                return ResourceManager.GetString("FlowDetail_LegendBaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LegendControl 的本地化字符串。
        /// </summary>
        public static string FlowDetail_LegendControl {
            get {
                return ResourceManager.GetString("FlowDetail_LegendControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LegendDefault 的本地化字符串。
        /// </summary>
        public static string FlowDetail_LegendDefault {
            get {
                return ResourceManager.GetString("FlowDetail_LegendDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LegendOtherInfo 的本地化字符串。
        /// </summary>
        public static string FlowDetail_LegendOtherInfo {
            get {
                return ResourceManager.GetString("FlowDetail_LegendOtherInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocationFrom 的本地化字符串。
        /// </summary>
        public static string FlowDetail_LocationFrom {
            get {
                return ResourceManager.GetString("FlowDetail_LocationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocationTo 的本地化字符串。
        /// </summary>
        public static string FlowDetail_LocationTo {
            get {
                return ResourceManager.GetString("FlowDetail_LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LotNo 的本地化字符串。
        /// </summary>
        public static string FlowDetail_LotNo {
            get {
                return ResourceManager.GetString("FlowDetail_LotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Machine 的本地化字符串。
        /// </summary>
        public static string FlowDetail_Machine {
            get {
                return ResourceManager.GetString("FlowDetail_Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ManufactureDate 的本地化字符串。
        /// </summary>
        public static string FlowDetail_ManufactureDate {
            get {
                return ResourceManager.GetString("FlowDetail_ManufactureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ManufactureParty 的本地化字符串。
        /// </summary>
        public static string FlowDetail_ManufactureParty {
            get {
                return ResourceManager.GetString("FlowDetail_ManufactureParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaxStock 的本地化字符串。
        /// </summary>
        public static string FlowDetail_MaxStock {
            get {
                return ResourceManager.GetString("FlowDetail_MaxStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MinLotSize 的本地化字符串。
        /// </summary>
        public static string FlowDetail_MinLotSize {
            get {
                return ResourceManager.GetString("FlowDetail_MinLotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MinUnitCount 的本地化字符串。
        /// </summary>
        public static string FlowDetail_MinUnitCount {
            get {
                return ResourceManager.GetString("FlowDetail_MinUnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mrp优先级 的本地化字符串。
        /// </summary>
        public static string FlowDetail_MrpPriority {
            get {
                return ResourceManager.GetString("FlowDetail_MrpPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MrpTotal 的本地化字符串。
        /// </summary>
        public static string FlowDetail_MrpTotal {
            get {
                return ResourceManager.GetString("FlowDetail_MrpTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MrpWeight 的本地化字符串。
        /// </summary>
        public static string FlowDetail_MrpWeight {
            get {
                return ResourceManager.GetString("FlowDetail_MrpWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderLotSize 的本地化字符串。
        /// </summary>
        public static string FlowDetail_OrderLotSize {
            get {
                return ResourceManager.GetString("FlowDetail_OrderLotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PartyFrom 的本地化字符串。
        /// </summary>
        public static string FlowDetail_PartyFrom {
            get {
                return ResourceManager.GetString("FlowDetail_PartyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PartyTo 的本地化字符串。
        /// </summary>
        public static string FlowDetail_PartyTo {
            get {
                return ResourceManager.GetString("FlowDetail_PartyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PickStrategy 的本地化字符串。
        /// </summary>
        public static string FlowDetail_PickStrategy {
            get {
                return ResourceManager.GetString("FlowDetail_PickStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PriceList 的本地化字符串。
        /// </summary>
        public static string FlowDetail_PriceList {
            get {
                return ResourceManager.GetString("FlowDetail_PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsInspect 的本地化字符串。
        /// </summary>
        public static string FlowDetail_ProductIsInspect {
            get {
                return ResourceManager.GetString("FlowDetail_ProductIsInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReceiveLotSize 的本地化字符串。
        /// </summary>
        public static string FlowDetail_ReceiveLotSize {
            get {
                return ResourceManager.GetString("FlowDetail_ReceiveLotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReferenceItemCode 的本地化字符串。
        /// </summary>
        public static string FlowDetail_ReferenceItemCode {
            get {
                return ResourceManager.GetString("FlowDetail_ReferenceItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark 的本地化字符串。
        /// </summary>
        public static string FlowDetail_Remark {
            get {
                return ResourceManager.GetString("FlowDetail_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReturnRouting 的本地化字符串。
        /// </summary>
        public static string FlowDetail_ReturnRouting {
            get {
                return ResourceManager.GetString("FlowDetail_ReturnRouting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RoundUpOption 的本地化字符串。
        /// </summary>
        public static string FlowDetail_RoundUpOption {
            get {
                return ResourceManager.GetString("FlowDetail_RoundUpOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Routing 的本地化字符串。
        /// </summary>
        public static string FlowDetail_Routing {
            get {
                return ResourceManager.GetString("FlowDetail_Routing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SafeStock 的本地化字符串。
        /// </summary>
        public static string FlowDetail_SafeStock {
            get {
                return ResourceManager.GetString("FlowDetail_SafeStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence 的本地化字符串。
        /// </summary>
        public static string FlowDetail_Sequence {
            get {
                return ResourceManager.GetString("FlowDetail_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShiftQuota 的本地化字符串。
        /// </summary>
        public static string FlowDetail_ShiftQuota {
            get {
                return ResourceManager.GetString("FlowDetail_ShiftQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartDate 的本地化字符串。
        /// </summary>
        public static string FlowDetail_StartDate {
            get {
                return ResourceManager.GetString("FlowDetail_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strategy 的本地化字符串。
        /// </summary>
        public static string FlowDetail_Strategy {
            get {
                return ResourceManager.GetString("FlowDetail_Strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SupplierLotNo 的本地化字符串。
        /// </summary>
        public static string FlowDetail_SupplierLotNo {
            get {
                return ResourceManager.GetString("FlowDetail_SupplierLotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnitCount 的本地化字符串。
        /// </summary>
        public static string FlowDetail_UnitCount {
            get {
                return ResourceManager.GetString("FlowDetail_UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnitCountDescription 的本地化字符串。
        /// </summary>
        public static string FlowDetail_UnitCountDescription {
            get {
                return ResourceManager.GetString("FlowDetail_UnitCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uom 的本地化字符串。
        /// </summary>
        public static string FlowDetail_Uom {
            get {
                return ResourceManager.GetString("FlowDetail_Uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uom1 的本地化字符串。
        /// </summary>
        public static string FlowDetail_Uom1 {
            get {
                return ResourceManager.GetString("FlowDetail_Uom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlowDetail has been updated successfully. 的本地化字符串。
        /// </summary>
        public static string FlowDetail_Updated {
            get {
                return ResourceManager.GetString("FlowDetail_Updated", resourceCulture);
            }
        }
    }
}
