//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.INV {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocationLotDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocationLotDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.INV.LocationLotDetail", typeof(LocationLotDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin.
        /// </summary>
        public static string Bin {
            get {
                return ResourceManager.GetString("Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc1.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode {0} is already in location {1}..
        /// </summary>
        public static string Errors_HuAlreadyInLocation {
            get {
                return ResourceManager.GetString("Errors_HuAlreadyInLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hu {0} is frozen, can&apos;t ship..
        /// </summary>
        public static string Errors_HuFrozenCantShip {
            get {
                return ResourceManager.GetString("Errors_HuFrozenCantShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hu {0} already in location {1}, can&apos;t receive..
        /// </summary>
        public static string Errors_HuIsAlreadyInLocation {
            get {
                return ResourceManager.GetString("Errors_HuIsAlreadyInLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode {0} is not in any location..
        /// </summary>
        public static string Errors_HuNotInAnyLocation {
            get {
                return ResourceManager.GetString("Errors_HuNotInAnyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode {0} is not in location {1}..
        /// </summary>
        public static string Errors_HuNotInSpecifiedLocation {
            get {
                return ResourceManager.GetString("Errors_HuNotInSpecifiedLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hu {0} not occupied by inspect order {1}, can&apos;t ship..
        /// </summary>
        public static string Errors_HuNotOccupiedByInspectOrder {
            get {
                return ResourceManager.GetString("Errors_HuNotOccupiedByInspectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hu {0} not occupied by miscorder {1}, can&apos;t ship..
        /// </summary>
        public static string Errors_HuNotOccupiedByMiscOrder {
            get {
                return ResourceManager.GetString("Errors_HuNotOccupiedByMiscOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hu {0} not occupied by pick list {1}, can&apos;t ship..
        /// </summary>
        public static string Errors_HuNotOccupiedByPickList {
            get {
                return ResourceManager.GetString("Errors_HuNotOccupiedByPickList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hu {0} not occupied by sequence order {1}, can&apos;t ship..
        /// </summary>
        public static string Errors_HuNotOccupiedBySequenceOrder {
            get {
                return ResourceManager.GetString("Errors_HuNotOccupiedBySequenceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hu {0} already occupied by inspect order {1}, can&apos;t ship..
        /// </summary>
        public static string Errors_HuOccupiedByInspectOrder {
            get {
                return ResourceManager.GetString("Errors_HuOccupiedByInspectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hu {0} already occupied by miscorder order {1}, can&apos;t ship..
        /// </summary>
        public static string Errors_HuOccupiedByMiscOrder {
            get {
                return ResourceManager.GetString("Errors_HuOccupiedByMiscOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hu {0} already occupied by pick list {1}, can&apos;t ship..
        /// </summary>
        public static string Errors_HuOccupiedByPickList {
            get {
                return ResourceManager.GetString("Errors_HuOccupiedByPickList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hu {0} already occupied by sequence order {1}, can&apos;t ship..
        /// </summary>
        public static string Errors_HuOccupiedBySequenceOrder {
            get {
                return ResourceManager.GetString("Errors_HuOccupiedBySequenceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode {0} qty is {1} not equals ship qty {2}..
        /// </summary>
        public static string Errors_HuQtyNotEqualShipQty {
            get {
                return ResourceManager.GetString("Errors_HuQtyNotEqualShipQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kit item can&apos;t process inventory..
        /// </summary>
        public static string Errors_KitItemCannotProcessInventory {
            get {
                return ResourceManager.GetString("Errors_KitItemCannotProcessInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0} don&apos;t have enough inventory in location {1}..
        /// </summary>
        public static string Errors_NotEnoughInventory {
            get {
                return ResourceManager.GetString("Errors_NotEnoughInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual item can&apos;t process inventory..
        /// </summary>
        public static string Errors_VirtualItemCannotProcessInventory {
            get {
                return ResourceManager.GetString("Errors_VirtualItemCannotProcessInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignment inventory already settled, void fail..
        /// </summary>
        public static string Errors_VoidFailNotEnoughSpecifyInventory {
            get {
                return ResourceManager.GetString("Errors_VoidFailNotEnoughSpecifyInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseUom.
        /// </summary>
        public static string LocationLotDetail_BaseUom {
            get {
                return ResourceManager.GetString("LocationLotDetail_BaseUom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin.
        /// </summary>
        public static string LocationLotDetail_Bin {
            get {
                return ResourceManager.GetString("LocationLotDetail_Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string LocationLotDetail_CreateDate {
            get {
                return ResourceManager.GetString("LocationLotDetail_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 方向.
        /// </summary>
        public static string LocationLotDetail_Direction {
            get {
                return ResourceManager.GetString("LocationLotDetail_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezed.
        /// </summary>
        public static string LocationLotDetail_Freezed {
            get {
                return ResourceManager.GetString("LocationLotDetail_Freezed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HuId.
        /// </summary>
        public static string LocationLotDetail_HuId {
            get {
                return ResourceManager.GetString("LocationLotDetail_HuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HuOption.
        /// </summary>
        public static string LocationLotDetail_HuOption {
            get {
                return ResourceManager.GetString("LocationLotDetail_HuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HuQty.
        /// </summary>
        public static string LocationLotDetail_HuQty {
            get {
                return ResourceManager.GetString("LocationLotDetail_HuQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HuUom.
        /// </summary>
        public static string LocationLotDetail_HuUom {
            get {
                return ResourceManager.GetString("LocationLotDetail_HuUom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string LocationLotDetail_Id {
            get {
                return ResourceManager.GetString("LocationLotDetail_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InventoryType.
        /// </summary>
        public static string LocationLotDetail_InventoryType {
            get {
                return ResourceManager.GetString("LocationLotDetail_InventoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有效.
        /// </summary>
        public static string LocationLotDetail_IsATP {
            get {
                return ResourceManager.GetString("LocationLotDetail_IsATP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsConsignment.
        /// </summary>
        public static string LocationLotDetail_IsConsignment {
            get {
                return ResourceManager.GetString("LocationLotDetail_IsConsignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsFreeze.
        /// </summary>
        public static string LocationLotDetail_IsFreeze {
            get {
                return ResourceManager.GetString("LocationLotDetail_IsFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IshideLotNo.
        /// </summary>
        public static string LocationLotDetail_IshideLotNo {
            get {
                return ResourceManager.GetString("LocationLotDetail_IshideLotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IshideSupper.
        /// </summary>
        public static string LocationLotDetail_IshideSupper {
            get {
                return ResourceManager.GetString("LocationLotDetail_IshideSupper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 零头.
        /// </summary>
        public static string LocationLotDetail_IsOdd {
            get {
                return ResourceManager.GetString("LocationLotDetail_IsOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string LocationLotDetail_Item {
            get {
                return ResourceManager.GetString("LocationLotDetail_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemDescription.
        /// </summary>
        public static string LocationLotDetail_ItemDescription {
            get {
                return ResourceManager.GetString("LocationLotDetail_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemTo.
        /// </summary>
        public static string LocationLotDetail_ItemTo {
            get {
                return ResourceManager.GetString("LocationLotDetail_ItemTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Version.
        /// </summary>
        public static string LocationLotDetail_ItemVersion {
            get {
                return ResourceManager.GetString("LocationLotDetail_ItemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyDate.
        /// </summary>
        public static string LocationLotDetail_LastModifyDate {
            get {
                return ResourceManager.GetString("LocationLotDetail_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string LocationLotDetail_Level {
            get {
                return ResourceManager.GetString("LocationLotDetail_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LocationLotDetail_Location {
            get {
                return ResourceManager.GetString("LocationLotDetail_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationTo.
        /// </summary>
        public static string LocationLotDetail_LocationTo {
            get {
                return ResourceManager.GetString("LocationLotDetail_LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotNo.
        /// </summary>
        public static string LocationLotDetail_LotNo {
            get {
                return ResourceManager.GetString("LocationLotDetail_LotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotNoFrom.
        /// </summary>
        public static string LocationLotDetail_LotNoFrom {
            get {
                return ResourceManager.GetString("LocationLotDetail_LotNoFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotNoTo.
        /// </summary>
        public static string LocationLotDetail_LotNoTo {
            get {
                return ResourceManager.GetString("LocationLotDetail_LotNoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制造时间.
        /// </summary>
        public static string LocationLotDetail_ManufactureDate {
            get {
                return ResourceManager.GetString("LocationLotDetail_ManufactureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManufactureParty.
        /// </summary>
        public static string LocationLotDetail_ManufactureParty {
            get {
                return ResourceManager.GetString("LocationLotDetail_ManufactureParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LocationLotDetail_Name {
            get {
                return ResourceManager.GetString("LocationLotDetail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OccupyReferenceNo.
        /// </summary>
        public static string LocationLotDetail_OccupyReferenceNo {
            get {
                return ResourceManager.GetString("LocationLotDetail_OccupyReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupy Type.
        /// </summary>
        public static string LocationLotDetail_OccupyType {
            get {
                return ResourceManager.GetString("LocationLotDetail_OccupyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanBill.
        /// </summary>
        public static string LocationLotDetail_PlanBill {
            get {
                return ResourceManager.GetString("LocationLotDetail_PlanBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string LocationLotDetail_Qty {
            get {
                return ResourceManager.GetString("LocationLotDetail_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QualityType.
        /// </summary>
        public static string LocationLotDetail_QualityType {
            get {
                return ResourceManager.GetString("LocationLotDetail_QualityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceItemCode.
        /// </summary>
        public static string LocationLotDetail_ReferenceItemCode {
            get {
                return ResourceManager.GetString("LocationLotDetail_ReferenceItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string LocationLotDetail_Region {
            get {
                return ResourceManager.GetString("LocationLotDetail_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegionTo.
        /// </summary>
        public static string LocationLotDetail_RegionTo {
            get {
                return ResourceManager.GetString("LocationLotDetail_RegionTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAPLocation.
        /// </summary>
        public static string LocationLotDetail_SAPLocation {
            get {
                return ResourceManager.GetString("LocationLotDetail_SAPLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMQty.
        /// </summary>
        public static string LocationLotDetail_SUMQty {
            get {
                return ResourceManager.GetString("LocationLotDetail_SUMQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TheFactory.
        /// </summary>
        public static string LocationLotDetail_TheFactory {
            get {
                return ResourceManager.GetString("LocationLotDetail_TheFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TheFactoryTo.
        /// </summary>
        public static string LocationLotDetail_TheFactoryTo {
            get {
                return ResourceManager.GetString("LocationLotDetail_TheFactoryTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeLocation.
        /// </summary>
        public static string LocationLotDetail_TypeLocation {
            get {
                return ResourceManager.GetString("LocationLotDetail_TypeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnFreezed.
        /// </summary>
        public static string LocationLotDetail_UnFreezed {
            get {
                return ResourceManager.GetString("LocationLotDetail_UnFreezed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitCount.
        /// </summary>
        public static string LocationLotDetail_UnitCount {
            get {
                return ResourceManager.GetString("LocationLotDetail_UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string LocationLotDetail_Uom {
            get {
                return ResourceManager.GetString("LocationLotDetail_Uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string LocationLotDetail_Version {
            get {
                return ResourceManager.GetString("LocationLotDetail_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        public static string LocationLotDetail_Workshop {
            get {
                return ResourceManager.GetString("LocationLotDetail_Workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkshopTo.
        /// </summary>
        public static string LocationLotDetail_WorkshopTo {
            get {
                return ResourceManager.GetString("LocationLotDetail_WorkshopTo", resourceCulture);
            }
        }
    }
}
