//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Party {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Party() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MD.Party", typeof(Party).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party has been Added  successfully..
        /// </summary>
        public static string Party_Added {
            get {
                return ResourceManager.GetString("Party_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Code.
        /// </summary>
        public static string Party_AddressCode {
            get {
                return ResourceManager.GetString("Party_AddressCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Party_AddressName {
            get {
                return ResourceManager.GetString("Party_AddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Party_Code {
            get {
                return ResourceManager.GetString("Party_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Party.
        /// </summary>
        public static string Party_CurrentParty {
            get {
                return ResourceManager.GetString("Party_CurrentParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer has been added successfully..
        /// </summary>
        public static string Party_Customer_Added {
            get {
                return ResourceManager.GetString("Party_Customer_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        public static string Party_Customer_Code {
            get {
                return ResourceManager.GetString("Party_Customer_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer has been Deleted successfully..
        /// </summary>
        public static string Party_Customer_Deleted {
            get {
                return ResourceManager.GetString("Party_Customer_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Customer.
        /// </summary>
        public static string Party_Customer_Edit_Title {
            get {
                return ResourceManager.GetString("Party_Customer_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer  has  been  Existing.
        /// </summary>
        public static string Party_Customer_Errors_Existing_Code {
            get {
                return ResourceManager.GetString("Party_Customer_Errors_Existing_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name  has  been  Existing.
        /// </summary>
        public static string Party_Customer_Errors_Existing_Name {
            get {
                return ResourceManager.GetString("Party_Customer_Errors_Existing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string Party_Customer_Name {
            get {
                return ResourceManager.GetString("Party_Customer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Customer.
        /// </summary>
        public static string Party_Customer_New_Title {
            get {
                return ResourceManager.GetString("Party_Customer_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Address.
        /// </summary>
        public static string Party_Customer_TabTitle_BillAddress {
            get {
                return ResourceManager.GetString("Party_Customer_TabTitle_BillAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Party_Customer_TabTitle_Customer {
            get {
                return ResourceManager.GetString("Party_Customer_TabTitle_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Address.
        /// </summary>
        public static string Party_Customer_TabTitle_ShipAddress {
            get {
                return ResourceManager.GetString("Party_Customer_TabTitle_ShipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer has been updated successfully..
        /// </summary>
        public static string Party_Customer_Updated {
            get {
                return ResourceManager.GetString("Party_Customer_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party has been Deleted successfully..
        /// </summary>
        public static string Party_Deleted {
            get {
                return ResourceManager.GetString("Party_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Party.
        /// </summary>
        public static string Party_Edit_Title {
            get {
                return ResourceManager.GetString("Party_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        public static string Party_IsActive {
            get {
                return ResourceManager.GetString("Party_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Party_Name {
            get {
                return ResourceManager.GetString("Party_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Party.
        /// </summary>
        public static string Party_New_Title {
            get {
                return ResourceManager.GetString("Party_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PurchaseGroup.
        /// </summary>
        public static string Party_PurchaseGroup {
            get {
                return ResourceManager.GetString("Party_PurchaseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Code.
        /// </summary>
        public static string Party_Region_Code {
            get {
                return ResourceManager.GetString("Party_Region_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Name.
        /// </summary>
        public static string Party_Region_Name {
            get {
                return ResourceManager.GetString("Party_Region_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier has been added successfully..
        /// </summary>
        public static string Party_Supplier_Added {
            get {
                return ResourceManager.GetString("Party_Supplier_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Code.
        /// </summary>
        public static string Party_Supplier_Code {
            get {
                return ResourceManager.GetString("Party_Supplier_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier has been Deleted successfully..
        /// </summary>
        public static string Party_Supplier_Deleted {
            get {
                return ResourceManager.GetString("Party_Supplier_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Supplier.
        /// </summary>
        public static string Party_Supplier_Edit_Title {
            get {
                return ResourceManager.GetString("Party_Supplier_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier  has  been  Existing.
        /// </summary>
        public static string Party_Supplier_Errors_Existing_Code {
            get {
                return ResourceManager.GetString("Party_Supplier_Errors_Existing_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name  has  been  Existing.
        /// </summary>
        public static string Party_Supplier_Errors_Existing_Name {
            get {
                return ResourceManager.GetString("Party_Supplier_Errors_Existing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        public static string Party_Supplier_Name {
            get {
                return ResourceManager.GetString("Party_Supplier_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Supplier.
        /// </summary>
        public static string Party_Supplier_New_Title {
            get {
                return ResourceManager.GetString("Party_Supplier_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortCode.
        /// </summary>
        public static string Party_Supplier_ShortCode {
            get {
                return ResourceManager.GetString("Party_Supplier_ShortCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Address.
        /// </summary>
        public static string Party_Supplier_TabTitle_BillAddress {
            get {
                return ResourceManager.GetString("Party_Supplier_TabTitle_BillAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Address.
        /// </summary>
        public static string Party_Supplier_TabTitle_ShipAddress {
            get {
                return ResourceManager.GetString("Party_Supplier_TabTitle_ShipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Party_Supplier_TabTitle_Supplier {
            get {
                return ResourceManager.GetString("Party_Supplier_TabTitle_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier has been updated successfully..
        /// </summary>
        public static string Party_Supplier_Updated {
            get {
                return ResourceManager.GetString("Party_Supplier_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party has been Updated successfully..
        /// </summary>
        public static string Party_Updated {
            get {
                return ResourceManager.GetString("Party_Updated", resourceCulture);
            }
        }
    }
}
