//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ORD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ORD.OrderMaster", typeof(OrderMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create order line, bom code {0} is inactive..
        /// </summary>
        public static string Errors_BomInActive {
            get {
                return ResourceManager.GetString("Errors_BomInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t mix different order type pick..
        /// </summary>
        public static string Errors_CannotMixOrderTypePick {
            get {
                return ResourceManager.GetString("Errors_CannotMixOrderTypePick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t mix different order type receive..
        /// </summary>
        public static string Errors_CannotMixOrderTypeReceive {
            get {
                return ResourceManager.GetString("Errors_CannotMixOrderTypeReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t mix different order type ship..
        /// </summary>
        public static string Errors_CannotMixOrderTypeShip {
            get {
                return ResourceManager.GetString("Errors_CannotMixOrderTypeShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started orders over the maximum allowed limit of the production line {0}..
        /// </summary>
        public static string Errors_ExcceedMaxOnlineCount {
            get {
                return ResourceManager.GetString("Errors_ExcceedMaxOnlineCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowIsNotCorrect.
        /// </summary>
        public static string Errors_FlowIsNotCorrect {
            get {
                return ResourceManager.GetString("Errors_FlowIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create order line, material {0} is inactive..
        /// </summary>
        public static string Errors_ItemInActive {
            get {
                return ResourceManager.GetString("Errors_ItemInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create order line, material {0} is virtual..
        /// </summary>
        public static string Errors_ItemIsVirtual {
            get {
                return ResourceManager.GetString("Errors_ItemIsVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create customer goods order line, material {0} is not for customer goods..
        /// </summary>
        public static string Errors_ItemNotCustomerGoods {
            get {
                return ResourceManager.GetString("Errors_ItemNotCustomerGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create work order line, material {0} is not for production..
        /// </summary>
        public static string Errors_ItemNotManufacture {
            get {
                return ResourceManager.GetString("Errors_ItemNotManufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create purchase order line, material {0} is not for purchase..
        /// </summary>
        public static string Errors_ItemNotPurchase {
            get {
                return ResourceManager.GetString("Errors_ItemNotPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create sales order line, material {0} is not for sales..
        /// </summary>
        public static string Errors_ItemNotSales {
            get {
                return ResourceManager.GetString("Errors_ItemNotSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create subcontract order line, material {0} is not for subcontract..
        /// </summary>
        public static string Errors_ItemNotSubContract {
            get {
                return ResourceManager.GetString("Errors_ItemNotSubContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bom detail can not be empty for order line {0}..
        /// </summary>
        public static string Errors_OrderBomDetailIsEmpty {
            get {
                return ResourceManager.GetString("Errors_OrderBomDetailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order line can not be empty..
        /// </summary>
        public static string Errors_OrderDetailIsEmpty {
            get {
                return ResourceManager.GetString("Errors_OrderDetailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order qty of material {0} is not fulfill unit count {1}..
        /// </summary>
        public static string Errors_OrderQtyNotFulfillUnitCount {
            get {
                return ResourceManager.GetString("Errors_OrderQtyNotFulfillUnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive line can not be empty..
        /// </summary>
        public static string Errors_ReceiveDetailIsEmpty {
            get {
                return ResourceManager.GetString("Errors_ReceiveDetailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {1} of order {0} receive qty excceed order qty..
        /// </summary>
        public static string Errors_ReceiveQtyExcceedOrderQty {
            get {
                return ResourceManager.GetString("Errors_ReceiveQtyExcceedOrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive qty of material {0} is not fulfill unit count {1}..
        /// </summary>
        public static string Errors_ReceiveQtyNotFulfillUnitCount {
            get {
                return ResourceManager.GetString("Errors_ReceiveQtyNotFulfillUnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive qty of material {0} is not fulfill unit count {1}..
        /// </summary>
        public static string Errors_RecieveQtyNotFulfillUnitCount {
            get {
                return ResourceManager.GetString("Errors_RecieveQtyNotFulfillUnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create order line, routing {0} is inactive..
        /// </summary>
        public static string Errors_RoutingInActive {
            get {
                return ResourceManager.GetString("Errors_RoutingInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create order line, scan code {0} is inactive..
        /// </summary>
        public static string Errors_ScanInActive {
            get {
                return ResourceManager.GetString("Errors_ScanInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEQOrderDetailMoreThanOne.
        /// </summary>
        public static string Errors_SEQOrderDetailMoreThanOne {
            get {
                return ResourceManager.GetString("Errors_SEQOrderDetailMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship line can not be empty..
        /// </summary>
        public static string Errors_ShipDetailIsEmpty {
            get {
                return ResourceManager.GetString("Errors_ShipDetailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {1} of order {0} ship qty excceed order qty..
        /// </summary>
        public static string Errors_ShipQtyExcceedOrderQty {
            get {
                return ResourceManager.GetString("Errors_ShipQtyExcceedOrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship qty of material {0} is not fulfill unit count {1}..
        /// </summary>
        public static string Errors_ShipQtyNotFulfillUnitCount {
            get {
                return ResourceManager.GetString("Errors_ShipQtyNotFulfillUnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add order binding for order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenAddOrderBinding {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenAddOrderBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add order bom detail for order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenAddOrderBomDetail {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenAddOrderBomDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add order line for order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenAddOrderDetail {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenAddOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete operation for order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenAddOrderOperation {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenAddOrderOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenDelete {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete order binding for order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenDeleteOrderBinding {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenDeleteOrderBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete order bom detail for order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenDeleteOrderBomDetail {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenDeleteOrderBomDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete order line for order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenDeleteOrderDetail {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenDeleteOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete order operation for order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenDeleteOrderOperation {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenDeleteOrderOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not expand bom for order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenExpandOrderBomDetail {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenExpandOrderBomDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not expand routing for order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenExpandOrderOperation {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenExpandOrderOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not expand routing and bom for order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenExpandOrderOperationAndBomDetail {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenExpandOrderOperationAndBomDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not modify order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenModify {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not modify order bom detail for order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenModifyOrderBomDetail {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenModifyOrderBomDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not modify order line for order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenModifyOrderDetail {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenModifyOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not modify order operation for order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenModifyOrderOperation {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenModifyOrderOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not receive order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenReceive {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not release order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenRelease {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not ship order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenShip {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not start order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenStart {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not modify order binding for order {0} which status is {1}..
        /// </summary>
        public static string Errors_StatusErrorWhenUpdateOrderBinding {
            get {
                return ResourceManager.GetString("Errors_StatusErrorWhenUpdateOrderBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster {0} Added.
        /// </summary>
        public static string OrderMaster_Added {
            get {
                return ResourceManager.GetString("OrderMaster_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AsnTemplate.
        /// </summary>
        public static string OrderMaster_AsnTemplate {
            get {
                return ResourceManager.GetString("OrderMaster_AsnTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string OrderMaster_Audit {
            get {
                return ResourceManager.GetString("OrderMaster_Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutomaticControl.
        /// </summary>
        public static string OrderMaster_AutomaticControl {
            get {
                return ResourceManager.GetString("OrderMaster_AutomaticControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarCodeOption.
        /// </summary>
        public static string OrderMaster_BarCodeOption {
            get {
                return ResourceManager.GetString("OrderMaster_BarCodeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseInfo.
        /// </summary>
        public static string OrderMaster_BaseInfo {
            get {
                return ResourceManager.GetString("OrderMaster_BaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster BatchCanceled.
        /// </summary>
        public static string OrderMaster_BatchCanceled {
            get {
                return ResourceManager.GetString("OrderMaster_BatchCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster BatchClosed.
        /// </summary>
        public static string OrderMaster_BatchClosed {
            get {
                return ResourceManager.GetString("OrderMaster_BatchClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster BatchDeleted.
        /// </summary>
        public static string OrderMaster_BatchDeleted {
            get {
                return ResourceManager.GetString("OrderMaster_BatchDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster BatchStarted.
        /// </summary>
        public static string OrderMaster_BatchStarted {
            get {
                return ResourceManager.GetString("OrderMaster_BatchStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster BatchSubmited.
        /// </summary>
        public static string OrderMaster_BatchSubmited {
            get {
                return ResourceManager.GetString("OrderMaster_BatchSubmited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillAddress.
        /// </summary>
        public static string OrderMaster_BillAddress {
            get {
                return ResourceManager.GetString("OrderMaster_BillAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillAddressDescript.
        /// </summary>
        public static string OrderMaster_BillAddressDescription {
            get {
                return ResourceManager.GetString("OrderMaster_BillAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillTerm.
        /// </summary>
        public static string OrderMaster_BillTerm {
            get {
                return ResourceManager.GetString("OrderMaster_BillTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingOrder.
        /// </summary>
        public static string OrderMaster_BindingOrder {
            get {
                return ResourceManager.GetString("OrderMaster_BindingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelDate.
        /// </summary>
        public static string OrderMaster_CancelDate {
            get {
                return ResourceManager.GetString("OrderMaster_CancelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster {0} Canceled.
        /// </summary>
        public static string OrderMaster_Canceled {
            get {
                return ResourceManager.GetString("OrderMaster_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelReason.
        /// </summary>
        public static string OrderMaster_CancelReason {
            get {
                return ResourceManager.GetString("OrderMaster_CancelReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelUserName.
        /// </summary>
        public static string OrderMaster_CancelUserName {
            get {
                return ResourceManager.GetString("OrderMaster_CancelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster {0} Checked.
        /// </summary>
        public static string OrderMaster_Checked {
            get {
                return ResourceManager.GetString("OrderMaster_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checker.
        /// </summary>
        public static string OrderMaster_Checker {
            get {
                return ResourceManager.GetString("OrderMaster_Checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster {0} Closed.
        /// </summary>
        public static string OrderMaster_Closed {
            get {
                return ResourceManager.GetString("OrderMaster_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseDate.
        /// </summary>
        public static string OrderMaster_CloseDate {
            get {
                return ResourceManager.GetString("OrderMaster_CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseUserName.
        /// </summary>
        public static string OrderMaster_CloseUserName {
            get {
                return ResourceManager.GetString("OrderMaster_CloseUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompleteAndFeed.
        /// </summary>
        public static string OrderMaster_CompleteAndFeed {
            get {
                return ResourceManager.GetString("OrderMaster_CompleteAndFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster {0} Completed.
        /// </summary>
        public static string OrderMaster_Completed {
            get {
                return ResourceManager.GetString("OrderMaster_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompleteDate.
        /// </summary>
        public static string OrderMaster_CompleteDate {
            get {
                return ResourceManager.GetString("OrderMaster_CompleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompleteUserName.
        /// </summary>
        public static string OrderMaster_CompleteUserName {
            get {
                return ResourceManager.GetString("OrderMaster_CompleteUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string OrderMaster_CreateDate {
            get {
                return ResourceManager.GetString("OrderMaster_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateHuOption.
        /// </summary>
        public static string OrderMaster_CreateHuOption {
            get {
                return ResourceManager.GetString("OrderMaster_CreateHuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUserName.
        /// </summary>
        public static string OrderMaster_CreateUserName {
            get {
                return ResourceManager.GetString("OrderMaster_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string OrderMaster_Currency {
            get {
                return ResourceManager.GetString("OrderMaster_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentOperation.
        /// </summary>
        public static string OrderMaster_CurrentOperation {
            get {
                return ResourceManager.GetString("OrderMaster_CurrentOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateFrom.
        /// </summary>
        public static string OrderMaster_DateFrom {
            get {
                return ResourceManager.GetString("OrderMaster_DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTo.
        /// </summary>
        public static string OrderMaster_DateTo {
            get {
                return ResourceManager.GetString("OrderMaster_DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateType.
        /// </summary>
        public static string OrderMaster_DateType {
            get {
                return ResourceManager.GetString("OrderMaster_DateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster {0} Deleted.
        /// </summary>
        public static string OrderMaster_Deleted {
            get {
                return ResourceManager.GetString("OrderMaster_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution.
        /// </summary>
        public static string OrderMaster_Distribution {
            get {
                return ResourceManager.GetString("OrderMaster_Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        public static string OrderMaster_Dock {
            get {
                return ResourceManager.GetString("OrderMaster_Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditOrderMaster.
        /// </summary>
        public static string OrderMaster_Edit_Title {
            get {
                return ResourceManager.GetString("OrderMaster_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EffectiveDate.
        /// </summary>
        public static string OrderMaster_EffectiveDate {
            get {
                return ResourceManager.GetString("OrderMaster_EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalOrderNo.
        /// </summary>
        public static string OrderMaster_ExternalOrderNo {
            get {
                return ResourceManager.GetString("OrderMaster_ExternalOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt ExternalOrderNo.
        /// </summary>
        public static string OrderMaster_ExternalOrderNo_Receipt {
            get {
                return ResourceManager.GetString("OrderMaster_ExternalOrderNo_Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SapOrderNo.
        /// </summary>
        public static string OrderMaster_ExternalOrderNo_Sap {
            get {
                return ResourceManager.GetString("OrderMaster_ExternalOrderNo_Sap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        public static string OrderMaster_ExternalSeqImport_DateTime {
            get {
                return ResourceManager.GetString("OrderMaster_ExternalSeqImport_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string OrderMaster_Flow {
            get {
                return ResourceManager.GetString("OrderMaster_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductLine.
        /// </summary>
        public static string OrderMaster_Flow_Production {
            get {
                return ResourceManager.GetString("OrderMaster_Flow_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowDescription.
        /// </summary>
        public static string OrderMaster_FlowDescription {
            get {
                return ResourceManager.GetString("OrderMaster_FlowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductLine Description.
        /// </summary>
        public static string OrderMaster_FlowDescription_Production {
            get {
                return ResourceManager.GetString("OrderMaster_FlowDescription_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FZOrderNo.
        /// </summary>
        public static string OrderMaster_FZOrderNo {
            get {
                return ResourceManager.GetString("OrderMaster_FZOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FZReceived.
        /// </summary>
        public static string OrderMaster_FZReceived {
            get {
                return ResourceManager.GetString("OrderMaster_FZReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HuTemplate.
        /// </summary>
        public static string OrderMaster_HuTemplate {
            get {
                return ResourceManager.GetString("OrderMaster_HuTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster Imported.
        /// </summary>
        public static string OrderMaster_Imported {
            get {
                return ResourceManager.GetString("OrderMaster_Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAsnUniqueReceive.
        /// </summary>
        public static string OrderMaster_IsAsnUniqueReceive {
            get {
                return ResourceManager.GetString("OrderMaster_IsAsnUniqueReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAutoBill.
        /// </summary>
        public static string OrderMaster_IsAutoBill {
            get {
                return ResourceManager.GetString("OrderMaster_IsAutoBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAutoReceive.
        /// </summary>
        public static string OrderMaster_IsAutoReceive {
            get {
                return ResourceManager.GetString("OrderMaster_IsAutoReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAutoRelease.
        /// </summary>
        public static string OrderMaster_IsAutoRelease {
            get {
                return ResourceManager.GetString("OrderMaster_IsAutoRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAutoShip.
        /// </summary>
        public static string OrderMaster_IsAutoShip {
            get {
                return ResourceManager.GetString("OrderMaster_IsAutoShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAutoStart.
        /// </summary>
        public static string OrderMaster_IsAutoStart {
            get {
                return ResourceManager.GetString("OrderMaster_IsAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCreatePickList.
        /// </summary>
        public static string OrderMaster_IsCreatePickList {
            get {
                return ResourceManager.GetString("OrderMaster_IsCreatePickList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsIndepentDemand.
        /// </summary>
        public static string OrderMaster_IsIndepentDemand {
            get {
                return ResourceManager.GetString("OrderMaster_IsIndepentDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsInspect.
        /// </summary>
        public static string OrderMaster_IsInspect {
            get {
                return ResourceManager.GetString("OrderMaster_IsInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsListPrice.
        /// </summary>
        public static string OrderMaster_IsListPrice {
            get {
                return ResourceManager.GetString("OrderMaster_IsListPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsManualCreateDetail.
        /// </summary>
        public static string OrderMaster_IsManualCreateDetail {
            get {
                return ResourceManager.GetString("OrderMaster_IsManualCreateDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsOpenOrder.
        /// </summary>
        public static string OrderMaster_IsOpenOrder {
            get {
                return ResourceManager.GetString("OrderMaster_IsOpenOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsOrderFulfillUC.
        /// </summary>
        public static string OrderMaster_IsOrderFulfillUC {
            get {
                return ResourceManager.GetString("OrderMaster_IsOrderFulfillUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsOrderPrinted.
        /// </summary>
        public static string OrderMaster_IsOrderPrinted {
            get {
                return ResourceManager.GetString("OrderMaster_IsOrderPrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPause.
        /// </summary>
        public static string OrderMaster_IsPause {
            get {
                return ResourceManager.GetString("OrderMaster_IsPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPickFromBin.
        /// </summary>
        public static string OrderMaster_IsPickFromBin {
            get {
                return ResourceManager.GetString("OrderMaster_IsPickFromBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPickListCreated.
        /// </summary>
        public static string OrderMaster_IsPickListCreated {
            get {
                return ResourceManager.GetString("OrderMaster_IsPickListCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPrintAsn.
        /// </summary>
        public static string OrderMaster_IsPrintAsn {
            get {
                return ResourceManager.GetString("OrderMaster_IsPrintAsn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPrintOrder.
        /// </summary>
        public static string OrderMaster_IsPrintOrder {
            get {
                return ResourceManager.GetString("OrderMaster_IsPrintOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPrintReceipt.
        /// </summary>
        public static string OrderMaster_IsPrintReceipt {
            get {
                return ResourceManager.GetString("OrderMaster_IsPrintReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsProductLinePause.
        /// </summary>
        public static string OrderMaster_IsProductLinePause {
            get {
                return ResourceManager.GetString("OrderMaster_IsProductLinePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsReceiveByOrder.
        /// </summary>
        public static string OrderMaster_IsReceiveByOrder {
            get {
                return ResourceManager.GetString("OrderMaster_IsReceiveByOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsReceiveExceed.
        /// </summary>
        public static string OrderMaster_IsReceiveExceed {
            get {
                return ResourceManager.GetString("OrderMaster_IsReceiveExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsReceiveFifo.
        /// </summary>
        public static string OrderMaster_IsReceiveFifo {
            get {
                return ResourceManager.GetString("OrderMaster_IsReceiveFifo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsReceiveFulfillUC.
        /// </summary>
        public static string OrderMaster_IsReceiveFulfillUC {
            get {
                return ResourceManager.GetString("OrderMaster_IsReceiveFulfillUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsReceiveScanHu.
        /// </summary>
        public static string OrderMaster_IsReceiveScanHu {
            get {
                return ResourceManager.GetString("OrderMaster_IsReceiveScanHu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsShipByOrder.
        /// </summary>
        public static string OrderMaster_IsShipByOrder {
            get {
                return ResourceManager.GetString("OrderMaster_IsShipByOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsShipExceed.
        /// </summary>
        public static string OrderMaster_IsShipExceed {
            get {
                return ResourceManager.GetString("OrderMaster_IsShipExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsShipFulfillUC.
        /// </summary>
        public static string OrderMaster_IsShipFulfillUC {
            get {
                return ResourceManager.GetString("OrderMaster_IsShipFulfillUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsShipScanHu.
        /// </summary>
        public static string OrderMaster_IsShipScanHu {
            get {
                return ResourceManager.GetString("OrderMaster_IsShipScanHu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string OrderMaster_Item {
            get {
                return ResourceManager.GetString("OrderMaster_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyDate.
        /// </summary>
        public static string OrderMaster_LastModifyDate {
            get {
                return ResourceManager.GetString("OrderMaster_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyUserName.
        /// </summary>
        public static string OrderMaster_LastModifyUserName {
            get {
                return ResourceManager.GetString("OrderMaster_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationFrom.
        /// </summary>
        public static string OrderMaster_LocationFrom {
            get {
                return ResourceManager.GetString("OrderMaster_LocationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationFromName.
        /// </summary>
        public static string OrderMaster_LocationFromName {
            get {
                return ResourceManager.GetString("OrderMaster_LocationFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationFromName_Procurement.
        /// </summary>
        public static string OrderMaster_LocationFromName_Production {
            get {
                return ResourceManager.GetString("OrderMaster_LocationFromName_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationTo.
        /// </summary>
        public static string OrderMaster_LocationTo {
            get {
                return ResourceManager.GetString("OrderMaster_LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationToName.
        /// </summary>
        public static string OrderMaster_LocationToName {
            get {
                return ResourceManager.GetString("OrderMaster_LocationToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationToName_Procurement.
        /// </summary>
        public static string OrderMaster_LocationToName_Production {
            get {
                return ResourceManager.GetString("OrderMaster_LocationToName_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewOrderMaster.
        /// </summary>
        public static string OrderMaster_New_Title {
            get {
                return ResourceManager.GetString("OrderMaster_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string OrderMaster_Operation {
            get {
                return ResourceManager.GetString("OrderMaster_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderControl.
        /// </summary>
        public static string OrderMaster_OrderControl {
            get {
                return ResourceManager.GetString("OrderMaster_OrderControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNo.
        /// </summary>
        public static string OrderMaster_OrderNo {
            get {
                return ResourceManager.GetString("OrderMaster_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNoName.
        /// </summary>
        public static string OrderMaster_OrderNoName {
            get {
                return ResourceManager.GetString("OrderMaster_OrderNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNoReturn.
        /// </summary>
        public static string OrderMaster_OrderNoReturn {
            get {
                return ResourceManager.GetString("OrderMaster_OrderNoReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderStrategy.
        /// </summary>
        public static string OrderMaster_OrderStrategy {
            get {
                return ResourceManager.GetString("OrderMaster_OrderStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderTemplate.
        /// </summary>
        public static string OrderMaster_OrderTemplate {
            get {
                return ResourceManager.GetString("OrderMaster_OrderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyFrom.
        /// </summary>
        public static string OrderMaster_PartyFrom {
            get {
                return ResourceManager.GetString("OrderMaster_PartyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyFrom_Production.
        /// </summary>
        public static string OrderMaster_PartyFrom_Production {
            get {
                return ResourceManager.GetString("OrderMaster_PartyFrom_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyFromName.
        /// </summary>
        public static string OrderMaster_PartyFromName {
            get {
                return ResourceManager.GetString("OrderMaster_PartyFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyFromName.
        /// </summary>
        public static string OrderMaster_PartyFromName_Production {
            get {
                return ResourceManager.GetString("OrderMaster_PartyFromName_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyTo.
        /// </summary>
        public static string OrderMaster_PartyTo {
            get {
                return ResourceManager.GetString("OrderMaster_PartyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyToName.
        /// </summary>
        public static string OrderMaster_PartyToName {
            get {
                return ResourceManager.GetString("OrderMaster_PartyToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster {0} Paused.
        /// </summary>
        public static string OrderMaster_Paused {
            get {
                return ResourceManager.GetString("OrderMaster_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PauseSequence.
        /// </summary>
        public static string OrderMaster_PauseSequence {
            get {
                return ResourceManager.GetString("OrderMaster_PauseSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PauseTime.
        /// </summary>
        public static string OrderMaster_PauseTime {
            get {
                return ResourceManager.GetString("OrderMaster_PauseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceList.
        /// </summary>
        public static string OrderMaster_PriceList {
            get {
                return ResourceManager.GetString("OrderMaster_PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintOption.
        /// </summary>
        public static string OrderMaster_PrintOption {
            get {
                return ResourceManager.GetString("OrderMaster_PrintOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string OrderMaster_Priority {
            get {
                return ResourceManager.GetString("OrderMaster_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement.
        /// </summary>
        public static string OrderMaster_Procurement {
            get {
                return ResourceManager.GetString("OrderMaster_Procurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return Procurement.
        /// </summary>
        public static string OrderMaster_Procurement_Rtn {
            get {
                return ResourceManager.GetString("OrderMaster_Procurement_Rtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string OrderMaster_Production {
            get {
                return ResourceManager.GetString("OrderMaster_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductLineFacility.
        /// </summary>
        public static string OrderMaster_ProductLineFacility {
            get {
                return ResourceManager.GetString("OrderMaster_ProductLineFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 质量状态.
        /// </summary>
        public static string OrderMaster_QualityType {
            get {
                return ResourceManager.GetString("OrderMaster_QualityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReCalculatePriceOption.
        /// </summary>
        public static string OrderMaster_ReCalculatePriceOption {
            get {
                return ResourceManager.GetString("OrderMaster_ReCalculatePriceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiptTemplate.
        /// </summary>
        public static string OrderMaster_ReceiptTemplate {
            get {
                return ResourceManager.GetString("OrderMaster_ReceiptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        public static string OrderMaster_Receive_Title {
            get {
                return ResourceManager.GetString("OrderMaster_Receive_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster {0} Received.
        /// </summary>
        public static string OrderMaster_Received {
            get {
                return ResourceManager.GetString("OrderMaster_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiveGapTo.
        /// </summary>
        public static string OrderMaster_ReceiveGapTo {
            get {
                return ResourceManager.GetString("OrderMaster_ReceiveGapTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceOrderNo.
        /// </summary>
        public static string OrderMaster_ReferenceOrderNo {
            get {
                return ResourceManager.GetString("OrderMaster_ReferenceOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefExtOrderNo.
        /// </summary>
        public static string OrderMaster_RefExtOrderNo {
            get {
                return ResourceManager.GetString("OrderMaster_RefExtOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseDate.
        /// </summary>
        public static string OrderMaster_ReleaseDate {
            get {
                return ResourceManager.GetString("OrderMaster_ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseUserName.
        /// </summary>
        public static string OrderMaster_ReleaseUserName {
            get {
                return ResourceManager.GetString("OrderMaster_ReleaseUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string OrderMaster_Remarks {
            get {
                return ResourceManager.GetString("OrderMaster_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequisitionList {0} Created.
        /// </summary>
        public static string OrderMaster_RequisitionList_Created {
            get {
                return ResourceManager.GetString("OrderMaster_RequisitionList_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item  {0} Not Create RequisitionList.
        /// </summary>
        public static string OrderMaster_RequisitionList_ItemNotCreated {
            get {
                return ResourceManager.GetString("OrderMaster_RequisitionList_ItemNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoOrderCreate.
        /// </summary>
        public static string OrderMaster_RequisitionList_NoOrderCreate {
            get {
                return ResourceManager.GetString("OrderMaster_RequisitionList_NoOrderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing.
        /// </summary>
        public static string OrderMaster_Routing {
            get {
                return ResourceManager.GetString("OrderMaster_Routing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster Saved.
        /// </summary>
        public static string OrderMaster_Saved {
            get {
                return ResourceManager.GetString("OrderMaster_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string OrderMaster_Sequence {
            get {
                return ResourceManager.GetString("OrderMaster_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string OrderMaster_Shift {
            get {
                return ResourceManager.GetString("OrderMaster_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship.
        /// </summary>
        public static string OrderMaster_Ship_Title {
            get {
                return ResourceManager.GetString("OrderMaster_Ship_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFrom.
        /// </summary>
        public static string OrderMaster_ShipFrom {
            get {
                return ResourceManager.GetString("OrderMaster_ShipFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromAddress.
        /// </summary>
        public static string OrderMaster_ShipFromAddress {
            get {
                return ResourceManager.GetString("OrderMaster_ShipFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromCell.
        /// </summary>
        public static string OrderMaster_ShipFromCell {
            get {
                return ResourceManager.GetString("OrderMaster_ShipFromCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromContact.
        /// </summary>
        public static string OrderMaster_ShipFromContact {
            get {
                return ResourceManager.GetString("OrderMaster_ShipFromContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发货方地址传真.
        /// </summary>
        public static string OrderMaster_ShipFromFax {
            get {
                return ResourceManager.GetString("OrderMaster_ShipFromFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromTel.
        /// </summary>
        public static string OrderMaster_ShipFromTel {
            get {
                return ResourceManager.GetString("OrderMaster_ShipFromTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster {0} Shipped.
        /// </summary>
        public static string OrderMaster_Shipped {
            get {
                return ResourceManager.GetString("OrderMaster_Shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipTo.
        /// </summary>
        public static string OrderMaster_ShipTo {
            get {
                return ResourceManager.GetString("OrderMaster_ShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToAddress.
        /// </summary>
        public static string OrderMaster_ShipToAddress {
            get {
                return ResourceManager.GetString("OrderMaster_ShipToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToCell.
        /// </summary>
        public static string OrderMaster_ShipToCell {
            get {
                return ResourceManager.GetString("OrderMaster_ShipToCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToContact.
        /// </summary>
        public static string OrderMaster_ShipToContact {
            get {
                return ResourceManager.GetString("OrderMaster_ShipToContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToFax.
        /// </summary>
        public static string OrderMaster_ShipToFax {
            get {
                return ResourceManager.GetString("OrderMaster_ShipToFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToTel.
        /// </summary>
        public static string OrderMaster_ShipToTel {
            get {
                return ResourceManager.GetString("OrderMaster_ShipToTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate.
        /// </summary>
        public static string OrderMaster_StartDate {
            get {
                return ResourceManager.GetString("OrderMaster_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster {0} Started.
        /// </summary>
        public static string OrderMaster_Started {
            get {
                return ResourceManager.GetString("OrderMaster_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTime.
        /// </summary>
        public static string OrderMaster_StartTime {
            get {
                return ResourceManager.GetString("OrderMaster_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartUserName.
        /// </summary>
        public static string OrderMaster_StartUserName {
            get {
                return ResourceManager.GetString("OrderMaster_StartUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string OrderMaster_Status {
            get {
                return ResourceManager.GetString("OrderMaster_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderMaster {0} Submited.
        /// </summary>
        public static string OrderMaster_Submited {
            get {
                return ResourceManager.GetString("OrderMaster_Submited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubType.
        /// </summary>
        public static string OrderMaster_SubType {
            get {
                return ResourceManager.GetString("OrderMaster_SubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hu Feed.
        /// </summary>
        public static string OrderMaster_Tab_HuFeed {
            get {
                return ResourceManager.GetString("OrderMaster_Tab_HuFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Feed.
        /// </summary>
        public static string OrderMaster_Tab_QtyFeed {
            get {
                return ResourceManager.GetString("OrderMaster_Tab_QtyFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TraceCode.
        /// </summary>
        public static string OrderMaster_TraceCode {
            get {
                return ResourceManager.GetString("OrderMaster_TraceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string OrderMaster_Type {
            get {
                return ResourceManager.GetString("OrderMaster_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string OrderMaster_Version {
            get {
                return ResourceManager.GetString("OrderMaster_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTime.
        /// </summary>
        public static string OrderMaster_WindowTime {
            get {
                return ResourceManager.GetString("OrderMaster_WindowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMSNO.
        /// </summary>
        public static string OrderMaster_WMSNO {
            get {
                return ResourceManager.GetString("OrderMaster_WMSNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WmSSeq.
        /// </summary>
        public static string OrderMaster_WmSSeq {
            get {
                return ResourceManager.GetString("OrderMaster_WmSSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScheduleLine Shipped.
        /// </summary>
        public static string ScheduleLine_Shipped {
            get {
                return ResourceManager.GetString("ScheduleLine_Shipped", resourceCulture);
            }
        }
    }
}
