//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.BIL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BillMstr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BillMstr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.BIL.BillMstr", typeof(BillMstr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ActingBill {
            get {
                return ResourceManager.GetString("ActingBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////     Runtime Version:4.0.30319.296
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace Resources.BIL {
        ///    using System;
        ///    
        ///    
        ///    /// &lt;summary&gt;
        ///    ///   A strongly-typed res [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ActingBill_Designer {
            get {
                return ResourceManager.GetString("ActingBill_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BatchBilling.
        /// </summary>
        public static string BillMstr_BatchBilling {
            get {
                return ResourceManager.GetString("BillMstr_BatchBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillAddress.
        /// </summary>
        public static string BillMstr_BillAddress {
            get {
                return ResourceManager.GetString("BillMstr_BillAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BilledAmount.
        /// </summary>
        public static string BillMstr_BilledAmount {
            get {
                return ResourceManager.GetString("BillMstr_BilledAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        public static string BillMstr_Billing {
            get {
                return ResourceManager.GetString("BillMstr_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillNo.
        /// </summary>
        public static string BillMstr_BillNo {
            get {
                return ResourceManager.GetString("BillMstr_BillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string BillMstr_CreateDate {
            get {
                return ResourceManager.GetString("BillMstr_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUserName.
        /// </summary>
        public static string BillMstr_CreateUserName {
            get {
                return ResourceManager.GetString("BillMstr_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillMstr_Distribution_Title.
        /// </summary>
        public static string BillMstr_Distribution_Title {
            get {
                return ResourceManager.GetString("BillMstr_Distribution_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EffectiveDate.
        /// </summary>
        public static string BillMstr_EffectiveDate {
            get {
                return ResourceManager.GetString("BillMstr_EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndTime.
        /// </summary>
        public static string BillMstr_EndTime {
            get {
                return ResourceManager.GetString("BillMstr_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalBillNo.
        /// </summary>
        public static string BillMstr_ExternalBillNo {
            get {
                return ResourceManager.GetString("BillMstr_ExternalBillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceDate.
        /// </summary>
        public static string BillMstr_InvoiceDate {
            get {
                return ResourceManager.GetString("BillMstr_InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceNo.
        /// </summary>
        public static string BillMstr_InvoiceNo {
            get {
                return ResourceManager.GetString("BillMstr_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution.
        /// </summary>
        public static string BillMstr_PartyName_Distribution {
            get {
                return ResourceManager.GetString("BillMstr_PartyName_Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyNm.
        /// </summary>
        public static string BillMstr_PartyNm {
            get {
                return ResourceManager.GetString("BillMstr_PartyNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceBillNo.
        /// </summary>
        public static string BillMstr_ReferenceBillNo {
            get {
                return ResourceManager.GetString("BillMstr_ReferenceBillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaleTitle.
        /// </summary>
        public static string BillMstr_SaleTitle {
            get {
                return ResourceManager.GetString("BillMstr_SaleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTime.
        /// </summary>
        public static string BillMstr_StartTime {
            get {
                return ResourceManager.GetString("BillMstr_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string BillMstr_Status {
            get {
                return ResourceManager.GetString("BillMstr_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string BillMstr_Title {
            get {
                return ResourceManager.GetString("BillMstr_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToCalculate.
        /// </summary>
        public static string BillMstr_ToCalculate {
            get {
                return ResourceManager.GetString("BillMstr_ToCalculate", resourceCulture);
            }
        }
    }
}
