//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Sconit.Service.SI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_sdmes0002/610/" +
            "zws_sdmes0002/zws_sdmes0002")]
        public string com_Sconit_Service_SI_SDMES0002_ZWS_SDMES0002 {
            get {
                return ((string)(this["com_Sconit_Service_SI_SDMES0002_ZWS_SDMES0002"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_mmmes0001/610/" +
            "zws_mmmes001/zws_mmmes001")]
        public string com_Sconit_Service_SI_MMMES0001_ZWS_MMMES0001 {
            get {
                return ((string)(this["com_Sconit_Service_SI_MMMES0001_ZWS_MMMES0001"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_ppmes0001/610/" +
            "zws_ppmes0001/zws_ppmes0001")]
        public string com_Sconit_Service_SI_PPMES0001_ZWS_PPMES0001 {
            get {
                return ((string)(this["com_Sconit_Service_SI_PPMES0001_ZWS_PPMES0001"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_ppmes0004/610/" +
            "zws_ppmes0004/zws_ppmes0004")]
        public string com_Sconit_Service_SI_PPMES0004_ZWS_PPMES0004 {
            get {
                return ((string)(this["com_Sconit_Service_SI_PPMES0004_ZWS_PPMES0004"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_ppmes0003/610/" +
            "zws_ppmes0003/zws_ppmes0003")]
        public string com_Sconit_Service_SI_PPMES0003_ZWS_PPMES0003 {
            get {
                return ((string)(this["com_Sconit_Service_SI_PPMES0003_ZWS_PPMES0003"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_ppmes0006/610/" +
            "zws_ppmes0006/zws_ppmes0006")]
        public string com_Sconit_Service_SI_PPMES0006_ZWS_PPMES0006 {
            get {
                return ((string)(this["com_Sconit_Service_SI_PPMES0006_ZWS_PPMES0006"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_mdmmes0001/610" +
            "/zws_mdmmes0001/zws_mdmmes0001")]
        public string com_Sconit_Service_SI_MDMMES0001_ZWS_MDMMES0001 {
            get {
                return ((string)(this["com_Sconit_Service_SI_MDMMES0001_ZWS_MDMMES0001"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_mdmmes0002/610" +
            "/zws_mdmmes0002/zws_mdmmes0002")]
        public string com_Sconit_Service_SI_MDMMES0002_ZWS_MDMMES0002 {
            get {
                return ((string)(this["com_Sconit_Service_SI_MDMMES0002_ZWS_MDMMES0002"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_mdmmes0003/610" +
            "/zws_mdmmes0003/zws_mdmmes0003")]
        public string com_Sconit_Service_SI_MDMMES0003_ZWS_MDMMES0003 {
            get {
                return ((string)(this["com_Sconit_Service_SI_MDMMES0003_ZWS_MDMMES0003"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_mdmmes0004/610" +
            "/zws_mdmmes0004/zws_mdmmes0004")]
        public string com_Sconit_Service_SI_MDMMES0004_ZWS_MDMMES0004 {
            get {
                return ((string)(this["com_Sconit_Service_SI_MDMMES0004_ZWS_MDMMES0004"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_mdmmes0005/610" +
            "/zws_mdmmes0005/zws_mdmmes0005")]
        public string com_Sconit_Service_SI_MDMMES0005_ZWS_MDMMES0005 {
            get {
                return ((string)(this["com_Sconit_Service_SI_MDMMES0005_ZWS_MDMMES0005"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_mdmmes0006/610" +
            "/zws_mdmmes0006/zws_mdmmes0006")]
        public string com_Sconit_Service_SI_MDMMES0006_ZWS_MDMMES0006 {
            get {
                return ((string)(this["com_Sconit_Service_SI_MDMMES0006_ZWS_MDMMES0006"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_stmes0001/610/" +
            "zws_stmes0001/zws_stmes0001")]
        public string com_Sconit_Service_SI_STMES0001_ZWS_STMES0001 {
            get {
                return ((string)(this["com_Sconit_Service_SI_STMES0001_ZWS_STMES0001"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_sdmes0001/610/" +
            "zws_sdmes0001/zws_sdmes0001")]
        public string com_Sconit_Service_SI_SDMES0001_ZWS_SDMES0001 {
            get {
                return ((string)(this["com_Sconit_Service_SI_SDMES0001_ZWS_SDMES0001"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_mesqty0001/610" +
            "/zws_mesqty0001/zws_mesqty0001")]
        public string com_Sconit_Service_SI_MESQTY0001_ZWS_MESQTY0001 {
            get {
                return ((string)(this["com_Sconit_Service_SI_MESQTY0001_ZWS_MESQTY0001"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_ppmes0005/610/" +
            "zws_ppmes0005/zws_ppmes0005")]
        public string com_Sconit_Service_SI_PPMES0005_ZWS_PPMES0005 {
            get {
                return ((string)(this["com_Sconit_Service_SI_PPMES0005_ZWS_PPMES0005"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_ppmes0002/610/" +
            "zws_ppmes0002/zws_ppmes0002")]
        public string com_Sconit_Service_SI_PPMES0002_ZWS_PPMES0002 {
            get {
                return ((string)(this["com_Sconit_Service_SI_PPMES0002_ZWS_PPMES0002"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SHQVSAPQ1.csaid.cooperintra.ctb:8000/sap/bc/srt/rfc/sap/zws_mmmes0002/610/" +
            "zws_mmmes0002/zws_mmmes0002")]
        public string com_Sconit_Service_SI_MMMES0002_ZWS_MMMES0002 {
            get {
                return ((string)(this["com_Sconit_Service_SI_MMMES0002_ZWS_MMMES0002"]));
            }
        }
    }
}
